package it.palsoftware.pastiera

/** Static rows and aggregate editors; individual user/device data is not indexed. */
internal fun inputDeviceSettingEntries(): List<SettingEntry> = listOf(
    SettingEntry("text_expansion.snippets.enabled", R.string.snippets_enable_title, summaryRes = R.string.snippets_title, route = SettingRoute(SettingsDestination.TextInput)),
    SettingEntry("text_expansion.snippets.tab", R.string.expansion_tab_title, summaryRes = R.string.snippets_title, route = SettingRoute(SettingsDestination.TextInput)),
    SettingEntry("text_expansion.snippets.enter", R.string.expansion_enter_title, summaryRes = R.string.snippets_title, route = SettingRoute(SettingsDestination.TextInput)),
    SettingEntry("text_expansion.snippets.space", R.string.expansion_space_title, summaryRes = R.string.snippets_title, route = SettingRoute(SettingsDestination.TextInput)),
    SettingEntry("text_expansion.snippets.prefix_space", R.string.expansion_prefix_space_title, summaryRes = R.string.snippets_title, route = SettingRoute(SettingsDestination.TextInput)),
    SettingEntry("text_expansion.emoji.enabled", R.string.emoji_shortcodes_enable_title, route = SettingRoute(SettingsDestination.TextInput)),
    SettingEntry("text_expansion.symbols.enabled", R.string.symbol_shortcodes_enable_title, route = SettingRoute(SettingsDestination.TextInput)),
    SettingEntry("text_expansion.emoji_symbols.tab", R.string.expansion_tab_title, summaryRes = R.string.emoji_symbols_title, route = SettingRoute(SettingsDestination.TextInput)),
    SettingEntry("text_expansion.emoji_symbols.enter", R.string.expansion_enter_title, summaryRes = R.string.emoji_symbols_title, route = SettingRoute(SettingsDestination.TextInput)),
    SettingEntry("text_expansion.emoji_symbols.exact_close", R.string.emoji_symbols_close_title, summaryRes = R.string.emoji_symbols_title, route = SettingRoute(SettingsDestination.TextInput)),
    SettingEntry("text_expansion.emoji_symbols.space", R.string.expansion_space_title, summaryRes = R.string.emoji_symbols_title, route = SettingRoute(SettingsDestination.TextInput)),
    SettingEntry("text_expansion.emoji_symbols.prefix_space", R.string.expansion_prefix_space_title, summaryRes = R.string.emoji_symbols_title, route = SettingRoute(SettingsDestination.TextInput)),
    SettingEntry("text_expansion.snippets.prefix", R.string.snippets_prefix_title, summaryRes = R.string.snippets_title, route = SettingRoute(SettingsDestination.TextInput)),
    SettingEntry("text_expansion.snippets.presentation", R.string.expansion_presentation_title, summaryRes = R.string.snippets_title, route = SettingRoute(SettingsDestination.TextInput)),
    SettingEntry("text_expansion.emoji_symbols.presentation", R.string.expansion_presentation_title, summaryRes = R.string.emoji_symbols_title, route = SettingRoute(SettingsDestination.TextInput)),
    SettingEntry("text_expansion.snippets.manage", R.string.snippets_manage_title, summaryRes = R.string.snippets_title, route = SettingRoute(SettingsDestination.TextInput)),
    SettingEntry("on_screen.number_row", R.string.software_keyboard_number_row_title, route = SettingRoute(SettingsDestination.KeyboardsDevices, keyboardsDevicesDestination = KeyboardsDevicesDestination.OnScreen)),
    SettingEntry("on_screen.left_modifier", R.string.software_keyboard_left_modifier_key_title, route = SettingRoute(SettingsDestination.KeyboardsDevices, keyboardsDevicesDestination = KeyboardsDevicesDestination.OnScreen)),
    SettingEntry("on_screen.right_modifier", R.string.software_keyboard_right_modifier_key_title, route = SettingRoute(SettingsDestination.KeyboardsDevices, keyboardsDevicesDestination = KeyboardsDevicesDestination.OnScreen)),
    SettingEntry("on_screen.nearest_key_touch", R.string.software_keyboard_nearest_key_touch_title, route = SettingRoute(SettingsDestination.KeyboardsDevices, keyboardsDevicesDestination = KeyboardsDevicesDestination.OnScreen)),
    SettingEntry("on_screen.layer_popup", R.string.software_keyboard_long_press_layer_popup_title, route = SettingRoute(SettingsDestination.KeyboardsDevices, keyboardsDevicesDestination = KeyboardsDevicesDestination.OnScreen)),
    SettingEntry("on_screen.layer_popup_below", R.string.software_keyboard_long_press_layer_popup_below_key_title, route = SettingRoute(SettingsDestination.KeyboardsDevices, keyboardsDevicesDestination = KeyboardsDevicesDestination.OnScreen), unavailableFallbackId = "on_screen.layer_popup", availabilityCheck = { SettingsManager.getSoftwareKeyboardLongPressLayerPopupEnabled(it) }),
    SettingEntry("on_screen.layout_style", R.string.software_keyboard_layout_style_title, route = SettingRoute(SettingsDestination.KeyboardsDevices, keyboardsDevicesDestination = KeyboardsDevicesDestination.OnScreen)),
    SettingEntry("on_screen.theme", R.string.software_keyboard_theme_link_title, route = SettingRoute(SettingsDestination.KeyboardsDevices, keyboardsDevicesDestination = KeyboardsDevicesDestination.OnScreen)),
    SettingEntry("hardware.titan2_layout", R.string.titan2_layout_title, route = SettingRoute(SettingsDestination.KeyboardsDevices, keyboardsDevicesDestination = KeyboardsDevicesDestination.BuiltIn)),
    SettingEntry("hardware.profile", R.string.hardware_keyboard_profile_select_label, route = SettingRoute(SettingsDestination.KeyboardsDevices, keyboardsDevicesDestination = KeyboardsDevicesDestination.BuiltIn)),
    SettingEntry("hardware.currency", R.string.keyboard_currency_symbol_title, route = SettingRoute(SettingsDestination.KeyboardsDevices, keyboardsDevicesDestination = KeyboardsDevicesDestination.BuiltIn)),
    SettingEntry("hardware.alt_editor", R.string.alt_key_editor_title, route = SettingRoute(SettingsDestination.KeyboardsDevices, keyboardsDevicesDestination = KeyboardsDevicesDestination.BuiltIn)),
    SettingEntry("clicks.number_row_repeat", R.string.clicks_number_row_repeat_title, route = SettingRoute(SettingsDestination.KeyboardsDevices, keyboardsDevicesDestination = KeyboardsDevicesDestination.PowerKeyboard)),
    SettingEntry("clicks.sticky_alt", R.string.clicks_sticky_alt_title, route = SettingRoute(SettingsDestination.KeyboardsDevices, keyboardsDevicesDestination = KeyboardsDevicesDestination.PowerKeyboard)),
    SettingEntry("clicks.sticky_shift", R.string.clicks_sticky_shift_title, route = SettingRoute(SettingsDestination.KeyboardsDevices, keyboardsDevicesDestination = KeyboardsDevicesDestination.PowerKeyboard)),
    SettingEntry("clicks.soft_return", R.string.clicks_soft_return_title, route = SettingRoute(SettingsDestination.KeyboardsDevices, keyboardsDevicesDestination = KeyboardsDevicesDestination.PowerKeyboard)),
    SettingEntry("clicks.cursor_mode", R.string.clicks_cursor_mode_title, route = SettingRoute(SettingsDestination.KeyboardsDevices, keyboardsDevicesDestination = KeyboardsDevicesDestination.PowerKeyboard)),
    SettingEntry("clicks.backlight", R.string.clicks_backlight_title, route = SettingRoute(SettingsDestination.KeyboardsDevices, keyboardsDevicesDestination = KeyboardsDevicesDestination.PowerKeyboard)),
    SettingEntry("clicks.backlight_brightness", R.string.clicks_backlight_brightness_title, route = SettingRoute(SettingsDestination.KeyboardsDevices, keyboardsDevicesDestination = KeyboardsDevicesDestination.PowerKeyboard)),
    SettingEntry("clicks.backlight_timeout_dialog", R.string.clicks_backlight_timeout_dialog_title, route = SettingRoute(SettingsDestination.KeyboardsDevices, keyboardsDevicesDestination = KeyboardsDevicesDestination.PowerKeyboard)),
    SettingEntry("clicks.idle_timeout_dialog", R.string.clicks_idle_timeout_dialog_title, route = SettingRoute(SettingsDestination.KeyboardsDevices, keyboardsDevicesDestination = KeyboardsDevicesDestination.PowerKeyboard)),
    SettingEntry("clicks.charging_automation", R.string.clicks_charging_automation_title, route = SettingRoute(SettingsDestination.KeyboardsDevices, keyboardsDevicesDestination = KeyboardsDevicesDestination.PowerKeyboard)),
    SettingEntry("clicks.charging_start", R.string.clicks_charging_start_title, route = SettingRoute(SettingsDestination.KeyboardsDevices, keyboardsDevicesDestination = KeyboardsDevicesDestination.PowerKeyboard)),
    SettingEntry("clicks.charging_stop", R.string.clicks_charging_stop_title, route = SettingRoute(SettingsDestination.KeyboardsDevices, keyboardsDevicesDestination = KeyboardsDevicesDestination.PowerKeyboard)),
    SettingEntry("clicks.show_keyboard_only_with_text_focus", R.string.clicks_show_keyboard_only_with_text_focus_title, route = SettingRoute(SettingsDestination.KeyboardsDevices, keyboardsDevicesDestination = KeyboardsDevicesDestination.PowerKeyboard)),
    SettingEntry("clicks.close_input_on_disconnect", R.string.clicks_close_input_on_disconnect_title, route = SettingRoute(SettingsDestination.KeyboardsDevices, keyboardsDevicesDestination = KeyboardsDevicesDestination.PowerKeyboard)),
    SettingEntry("clicks.firmware_updates", R.string.clicks_firmware_updates_title, route = SettingRoute(SettingsDestination.KeyboardsDevices, keyboardsDevicesDestination = KeyboardsDevicesDestination.PowerKeyboard)),
    SettingEntry("clicks.recommended_settings", R.string.clicks_recommended_settings_title, route = SettingRoute(SettingsDestination.KeyboardsDevices, keyboardsDevicesDestination = KeyboardsDevicesDestination.PowerKeyboard)),
    SettingEntry("clicks.button_bindings", R.string.clicks_button_bindings_title, route = SettingRoute(SettingsDestination.KeyboardsDevices, keyboardsDevicesDestination = KeyboardsDevicesDestination.PowerKeyboard)),
    SettingEntry("clicks.number_row", R.string.clicks_number_row_title, route = SettingRoute(SettingsDestination.KeyboardsDevices, keyboardsDevicesDestination = KeyboardsDevicesDestination.PowerKeyboard)),
    SettingEntry("clicks.host_slots", R.string.clicks_host_slots_title, route = SettingRoute(SettingsDestination.KeyboardsDevices, keyboardsDevicesDestination = KeyboardsDevicesDestination.PowerKeyboard)),
    SettingEntry("clicks.buttons.launcher_button", R.string.clicks_launcher_button_title, route = SettingRoute(SettingsDestination.KeyboardsDevices, keyboardsDevicesDestination = KeyboardsDevicesDestination.PowerKeyboard)),
    SettingEntry("clicks.buttons.red_button", R.string.clicks_red_button_title, route = SettingRoute(SettingsDestination.KeyboardsDevices, keyboardsDevicesDestination = KeyboardsDevicesDestination.PowerKeyboard)),
    SettingEntry("clicks.buttons.alt_button", R.string.clicks_alt_button_title, route = SettingRoute(SettingsDestination.KeyboardsDevices, keyboardsDevicesDestination = KeyboardsDevicesDestination.PowerKeyboard)),
    SettingEntry("clicks.buttons.microphone_button", R.string.clicks_microphone_button_title, route = SettingRoute(SettingsDestination.KeyboardsDevices, keyboardsDevicesDestination = KeyboardsDevicesDestination.PowerKeyboard)),
    SettingEntry("clicks.number_row_input_mode", R.string.clicks_number_row_input_mode_title, route = SettingRoute(SettingsDestination.KeyboardsDevices, keyboardsDevicesDestination = KeyboardsDevicesDestination.PowerKeyboard)),
    SettingEntry("clicks.release_order", R.string.clicks_release_order_title, route = SettingRoute(SettingsDestination.KeyboardsDevices, keyboardsDevicesDestination = KeyboardsDevicesDestination.PowerKeyboard)),
    SettingEntry("sym.auto_close", R.string.sym_auto_close_title, route = SettingRoute(SettingsDestination.Modifiers, symCustomization = true)),
    SettingEntry("sym.auto_close_touch", R.string.sym_auto_close_touch_title, route = SettingRoute(SettingsDestination.Modifiers, symCustomization = true)),
    SettingEntry("sym.emoji_height", R.string.emoji_picker_expanded_height_title, route = SettingRoute(SettingsDestination.Modifiers, symCustomization = true)),
    SettingEntry("sym.pages", R.string.sym_swap_pages_title, route = SettingRoute(SettingsDestination.Modifiers, symCustomization = true)),
    SettingEntry("clicks.charging_reserve", R.string.clicks_charging_reserve_title, route = SettingRoute(SettingsDestination.KeyboardsDevices, keyboardsDevicesDestination = KeyboardsDevicesDestination.PowerKeyboard)),
    SettingEntry("clicks.manual_wireless_charging", R.string.clicks_manual_wireless_charging_title, route = SettingRoute(SettingsDestination.KeyboardsDevices, keyboardsDevicesDestination = KeyboardsDevicesDestination.PowerKeyboard)),
)
