package it.palsoftware.pastiera

import android.app.Activity
import android.content.ClipData
import android.content.ClipboardManager
import android.content.Context
import android.content.Intent
import android.content.SharedPreferences
import android.os.Build
import android.os.Bundle
import android.os.SystemClock
import android.provider.Settings
import android.view.KeyEvent
import android.view.InputDevice
import android.view.inputmethod.InputMethodManager
import android.widget.Toast
import androidx.activity.ComponentActivity
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.compose.setContent
import androidx.activity.enableEdgeToEdge
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.animation.*
import androidx.compose.animation.core.tween
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.horizontalScroll
import androidx.compose.foundation.text.selection.SelectionContainer
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.runtime.saveable.rememberSaveable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.size
import androidx.compose.ui.graphics.Color
import androidx.compose.foundation.background
import androidx.compose.ui.platform.LocalDensity
import androidx.compose.foundation.layout.WindowInsets
import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.ui.text.input.KeyboardCapitalization
import it.palsoftware.pastiera.R
import it.palsoftware.pastiera.inputmethod.DebugCaptureStore
import it.palsoftware.pastiera.inputmethod.KeyboardEventTracker
import it.palsoftware.pastiera.inputmethod.NotificationHelper
import it.palsoftware.pastiera.inputmethod.subtype.AdditionalSubtypeUtils
import it.palsoftware.pastiera.ui.CustomTopBar
import it.palsoftware.pastiera.ui.theme.PastieraTheme
import it.palsoftware.pastiera.BuildConfig
import it.palsoftware.pastiera.update.checkForUpdate
import it.palsoftware.pastiera.update.showUpdateDialog
import it.palsoftware.pastiera.update.UpdateCheckWorker
import it.palsoftware.pastiera.update.shouldUseGithubUpdateChecks
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowForward
import androidx.compose.material.icons.filled.Settings
import androidx.compose.material.icons.filled.Warning
import androidx.compose.material.icons.filled.Keyboard
import androidx.compose.material.icons.filled.BugReport
import androidx.activity.compose.BackHandler
import androidx.compose.ui.window.Dialog
import androidx.compose.ui.window.DialogProperties
import it.palsoftware.pastiera.inputmethod.DeviceSpecific
import kotlinx.coroutines.delay
import java.security.MessageDigest
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale
import java.util.TimeZone

class MainActivity : LocalizedComponentActivity() {
    
    data class KeyEventInfo(
        val keyCode: Int,
        val keyCodeName: String,
        val action: String,
        val unicodeChar: Int,
        val isAltPressed: Boolean,
        val isShiftPressed: Boolean,
        val isCtrlPressed: Boolean
    )

    private fun remapHardwareEvent(keyCode: Int, event: KeyEvent?): Pair<Int, KeyEvent?> {
        val remapped = DeviceSpecific.remapHardwareKeyEvent(
            keyCode,
            event,
            SettingsManager.getPhysicalKeyboardProfileOverride(this)
        )
        return remapped.keyCode to remapped.event
    }
    
    override fun onKeyDown(keyCode_: Int, event_: KeyEvent?): Boolean {
        val (keyCode, event) = remapHardwareEvent(keyCode_, event_)
        // Notify only events that are not output keycodes generated by the service.
        // Output keycodes (DPAD, TAB, PAGE_UP, PAGE_DOWN, ESCAPE) without modifiers
        // are generated by the service and the original event with output has already been reported.
        if (event != null) {
            val isOutputKeyCode = keyCode in listOf(
                KeyEvent.KEYCODE_DPAD_UP,
                KeyEvent.KEYCODE_DPAD_DOWN,
                KeyEvent.KEYCODE_DPAD_LEFT,
                KeyEvent.KEYCODE_DPAD_RIGHT,
                KeyEvent.KEYCODE_TAB,
                KeyEvent.KEYCODE_PAGE_UP,
                KeyEvent.KEYCODE_PAGE_DOWN,
                KeyEvent.KEYCODE_ESCAPE
            )
            val hasModifiers = event.isAltPressed || event.isShiftPressed || event.isCtrlPressed
            
            // Ignora i keycode di output senza modificatori (sono generati dal servizio)
            if (!isOutputKeyCode || hasModifiers) {
                KeyboardEventTracker.notifyKeyEvent(keyCode, event, "KEY_DOWN", origin = "activity")
            }
        }
        return super.onKeyDown(keyCode, event)
    }
    
    override fun onKeyUp(keyCode_: Int, event_: KeyEvent?): Boolean {
        val (keyCode, event) = remapHardwareEvent(keyCode_, event_)
        // Notify only events that are not output keycodes generated by the service.
        if (event != null) {
            val isOutputKeyCode = keyCode in listOf(
                KeyEvent.KEYCODE_DPAD_UP,
                KeyEvent.KEYCODE_DPAD_DOWN,
                KeyEvent.KEYCODE_DPAD_LEFT,
                KeyEvent.KEYCODE_DPAD_RIGHT,
                KeyEvent.KEYCODE_TAB,
                KeyEvent.KEYCODE_PAGE_UP,
                KeyEvent.KEYCODE_PAGE_DOWN,
                KeyEvent.KEYCODE_ESCAPE
            )
            val hasModifiers = event.isAltPressed || event.isShiftPressed || event.isCtrlPressed
            
            // Ignore output keycodes without modifiers (they are generated by the service)
            if (!isOutputKeyCode || hasModifiers) {
                KeyboardEventTracker.notifyKeyEvent(keyCode, event, "KEY_UP", origin = "activity")
            }
        }
        return super.onKeyUp(keyCode, event)
    }
    
    private fun getKeyCodeName(keyCode: Int): String {
        return when (keyCode) {
            KeyEvent.KEYCODE_Q -> "KEYCODE_Q"
            KeyEvent.KEYCODE_W -> "KEYCODE_W"
            KeyEvent.KEYCODE_E -> "KEYCODE_E"
            KeyEvent.KEYCODE_R -> "KEYCODE_R"
            KeyEvent.KEYCODE_T -> "KEYCODE_T"
            KeyEvent.KEYCODE_Y -> "KEYCODE_Y"
            KeyEvent.KEYCODE_U -> "KEYCODE_U"
            KeyEvent.KEYCODE_I -> "KEYCODE_I"
            KeyEvent.KEYCODE_O -> "KEYCODE_O"
            KeyEvent.KEYCODE_P -> "KEYCODE_P"
            KeyEvent.KEYCODE_A -> "KEYCODE_A"
            KeyEvent.KEYCODE_S -> "KEYCODE_S"
            KeyEvent.KEYCODE_D -> "KEYCODE_D"
            KeyEvent.KEYCODE_F -> "KEYCODE_F"
            KeyEvent.KEYCODE_G -> "KEYCODE_G"
            KeyEvent.KEYCODE_H -> "KEYCODE_H"
            KeyEvent.KEYCODE_J -> "KEYCODE_J"
            KeyEvent.KEYCODE_K -> "KEYCODE_K"
            KeyEvent.KEYCODE_L -> "KEYCODE_L"
            KeyEvent.KEYCODE_Z -> "KEYCODE_Z"
            KeyEvent.KEYCODE_X -> "KEYCODE_X"
            KeyEvent.KEYCODE_C -> "KEYCODE_C"
            KeyEvent.KEYCODE_V -> "KEYCODE_V"
            KeyEvent.KEYCODE_B -> "KEYCODE_B"
            KeyEvent.KEYCODE_N -> "KEYCODE_N"
            KeyEvent.KEYCODE_M -> "KEYCODE_M"
            KeyEvent.KEYCODE_SPACE -> "KEYCODE_SPACE"
            KeyEvent.KEYCODE_ENTER -> "KEYCODE_ENTER"
            KeyEvent.KEYCODE_DEL -> "KEYCODE_DEL"
            KeyEvent.KEYCODE_BACK -> "KEYCODE_BACK"
            else -> "KEYCODE_$keyCode"
        }
    }
    
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        
        // Check if tutorial has been completed
        if (!SettingsManager.isTutorialCompleted(this)) {
            val intent = Intent(this, TutorialActivity::class.java)
            startActivity(intent)
            finish()
            return
        }

        if (
            BuildConfig.RELEASE_CHANNEL != "nightly" &&
            SettingsManager.shouldShowWhatsNew(this, BuildConfig.VERSION_NAME)
        ) {
            val intent = Intent(this, TutorialActivity::class.java).apply {
                putExtra(TutorialActivity.EXTRA_UPDATE_TUTORIAL, true)
            }
            startActivity(intent)
            finish()
            return
        }
        
        // Register additional subtypes (custom input styles) when app starts
        // This ensures dynamic languages are available when IME is enabled
        AdditionalSubtypeUtils.registerAdditionalSubtypes(applicationContext)
        
        if (shouldUseGithubUpdateChecks(this)) {
            // Schedule periodic background update checks (every 24 hours).
            UpdateCheckWorker.schedule(applicationContext)
        }
        
        enableEdgeToEdge()
        setContent {
            PastieraTheme {
                Box(modifier = Modifier.fillMaxSize()) {
                    Scaffold(modifier = Modifier.fillMaxSize()) { innerPadding ->
                        KeyboardSetupScreen(
                            modifier = Modifier
                                .padding(innerPadding)
                                .fillMaxSize(),
                            activity = this@MainActivity
                        )
                    }
                    
                    // Status bar overlay - responsive to theme
                    val statusBarHeight = WindowInsets.statusBars.asPaddingValues().calculateTopPadding()
                    val isDarkTheme = isSystemInDarkTheme()
                    val overlayColor = if (isDarkTheme) {
                        // Dark theme: use black overlay
                        Color.Black.copy(alpha = 0.3f)
                    } else {
                        // Light theme: use white overlay
                        Color.White.copy(alpha = 0.2f)
                    }
                    
                    Box(
                        modifier = Modifier
                            .fillMaxWidth()
                            .height(statusBarHeight)
                            .background(overlayColor)
                    )
                }
            }
        }
    }
}

private data class RecordedKeyboardEvent(
    val wallTimestampMs: Long,
    val uptimeTimestampMs: Long?,
    val deltaMs: Long?,
    val event: KeyboardEventTracker.KeyEventInfo
)

@Composable
private fun DebugReportViewerDialog(
    report: String,
    onDismiss: () -> Unit,
    onCopy: () -> Unit,
    onShare: () -> Unit
) {
    val colorScheme = MaterialTheme.colorScheme
    val scroll = rememberScrollState()
    val lines = remember(report) { report.lines() }

    Dialog(
        onDismissRequest = onDismiss,
        properties = DialogProperties(usePlatformDefaultWidth = false)
    ) {
        Surface(
            modifier = Modifier.fillMaxSize(),
            color = colorScheme.surface
        ) {
            Column(
                modifier = Modifier
                    .fillMaxSize()
                    .padding(12.dp),
                verticalArrangement = Arrangement.spacedBy(8.dp)
            ) {
                Row(
                    modifier = Modifier.fillMaxWidth(),
                    horizontalArrangement = Arrangement.SpaceBetween,
                    verticalAlignment = Alignment.CenterVertically
                ) {
                    Text(
                        text = stringResource(R.string.debug_report_viewer_title),
                        style = MaterialTheme.typography.titleMedium,
                        fontWeight = FontWeight.SemiBold,
                        maxLines = 1,
                        overflow = TextOverflow.Ellipsis
                    )
                    TextButton(onClick = onDismiss) {
                        Text(stringResource(R.string.close))
                    }
                }
                Row(
                    modifier = Modifier
                        .fillMaxWidth()
                        .horizontalScroll(rememberScrollState()),
                    horizontalArrangement = Arrangement.spacedBy(8.dp),
                    verticalAlignment = Alignment.CenterVertically
                ) {
                    OutlinedButton(onClick = onCopy) {
                        Text(stringResource(R.string.debug_recorder_copy))
                    }
                    OutlinedButton(onClick = onShare) {
                        Text(stringResource(R.string.debug_recorder_share))
                    }
                }
                SelectionContainer {
                    Column(
                        modifier = Modifier
                            .fillMaxWidth()
                            .weight(1f)
                            .verticalScroll(scroll)
                    ) {
                        lines.forEach { line ->
                            Text(
                                text = line,
                                style = MaterialTheme.typography.bodySmall,
                                fontFamily = FontFamily.Monospace,
                                color = debugReportLineColor(line, colorScheme)
                            )
                        }
                    }
                }
            }
        }
    }
}

private fun debugReportLineColor(line: String, colors: ColorScheme): Color {
    val trimmed = line.trim()
    return when {
        trimmed.startsWith("===") -> colors.primary
        trimmed.startsWith("[") && trimmed.endsWith("]") -> colors.tertiary
        trimmed.startsWith("sha256=") -> colors.primary
        trimmed.startsWith("(no ") || trimmed == "n/a" || trimmed.isEmpty() -> colors.onSurfaceVariant
        " | " in line -> colors.onSurface
        "=" in line -> colors.secondary
        else -> colors.onSurfaceVariant
    }
}

@Composable
fun KeyboardSetupScreen(
    modifier: Modifier = Modifier,
    activity: MainActivity
) {
    val context = LocalContext.current
    
    var testText by remember { mutableStateOf("") }
    val rawLastKeyEventState = remember { mutableStateOf<KeyboardEventTracker.KeyEventInfo?>(null) }
    val rawLastKeyEvent by rawLastKeyEventState
    var displayedLastKeyEvent by remember { mutableStateOf<KeyboardEventTracker.KeyEventInfo?>(null) }
    var lastNonBackKeyEvent by remember { mutableStateOf<KeyboardEventTracker.KeyEventInfo?>(null) }
    var ignoreKeyboardCloseBackEvent by rememberSaveable { mutableStateOf(true) }
    var isRecording by rememberSaveable { mutableStateOf(false) }
    var recordStartedAtMs by rememberSaveable { mutableStateOf<Long?>(null) }
    var lastRecordedAtMs by rememberSaveable { mutableStateOf<Long?>(null) }
    var includeSuggestionsInExport by rememberSaveable { mutableStateOf(false) }
    var showDebugReportViewer by rememberSaveable { mutableStateOf(false) }
    var latestDebugReport by rememberSaveable { mutableStateOf("") }
    val recordedEvents = remember { mutableStateListOf<RecordedKeyboardEvent>() }
    
    // State for IME status
    var isPastieraEnabled by remember { mutableStateOf(false) }
    var isPastieraSelected by remember { mutableStateOf(false) }
    
    // Check IME status
    LaunchedEffect(Unit) {
        checkImeStatus(context) { enabled, selected ->
            isPastieraEnabled = enabled
            isPastieraSelected = selected
        }
    }
    
    // Refresh IME status periodically and when activity resumes
    LaunchedEffect(Unit) {
        // Check status every 2 seconds when screen is visible
        while (true) {
            kotlinx.coroutines.delay(2000)
            checkImeStatus(context) { enabled, selected ->
                isPastieraEnabled = enabled
                isPastieraSelected = selected
            }
        }
    }
    
    // Request notification permission (Android 13+)
    val requestPermissionLauncher = rememberLauncherForActivityResult(
        contract = ActivityResultContracts.RequestPermission()
    ) { isGranted: Boolean ->
        if (isGranted) {
            android.util.Log.d("MainActivity", "Notification permission granted")
        } else {
            android.util.Log.w("MainActivity", "Notification permission denied")
        }
    }
    
    // Request notification permission when the composable is created (Android 13+ only)
    LaunchedEffect(Unit) {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
            if (!NotificationHelper.hasNotificationPermission(context)) {
                requestPermissionLauncher.launch(android.Manifest.permission.POST_NOTIFICATIONS)
            }
        }
    }
    
    // Connect state to the global tracker
    LaunchedEffect(Unit) {
        KeyboardEventTracker.registerState(rawLastKeyEventState)
    }

    // Recording follows the raw stream; display filtering is handled separately below.
    LaunchedEffect(rawLastKeyEvent) {
        val event = rawLastKeyEvent ?: return@LaunchedEffect
        if (event.keyCode != KeyEvent.KEYCODE_BACK) {
            lastNonBackKeyEvent = event
        }
        if (isRecording) {
            val nowWall = System.currentTimeMillis()
            val nowUptime = SystemClock.uptimeMillis()
            val eventUptime = event.eventTimeUptimeMs.takeIf { it > 0L }
            val wallTimestampMs = eventUptime?.let { nowWall - (nowUptime - it) } ?: nowWall
            val deltaMs = lastRecordedAtMs?.let { previous -> (wallTimestampMs - previous).coerceAtLeast(0L) }
            recordedEvents.add(
                RecordedKeyboardEvent(
                    wallTimestampMs = wallTimestampMs,
                    uptimeTimestampMs = eventUptime,
                    deltaMs = deltaMs,
                    event = event
                )
            )
            lastRecordedAtMs = wallTimestampMs
        }
    }

    // Keep the latest useful debug event visible when keyboard close/navigation emits BACK.
    LaunchedEffect(rawLastKeyEvent, ignoreKeyboardCloseBackEvent, lastNonBackKeyEvent) {
        val event = rawLastKeyEvent
        displayedLastKeyEvent = when {
            event == null -> null
            ignoreKeyboardCloseBackEvent && event.keyCode == KeyEvent.KEYCODE_BACK -> lastNonBackKeyEvent
            else -> event
        }
    }
    
    // Clear state when the composable is removed
    DisposableEffect(Unit) {
        onDispose {
            KeyboardEventTracker.unregisterState()
        }
    }
    
    // Automatic update check on screen open (only once, respecting dismissed releases)
    if (shouldUseGithubUpdateChecks(context)) {
        LaunchedEffect(Unit) {
            checkForUpdate(
                context = context,
                currentVersion = BuildConfig.VERSION_NAME,
                releaseChannel = BuildConfig.RELEASE_CHANNEL,
                ignoreDismissedReleases = true
            ) { hasUpdate, latestVersion, downloadUrl, releasePageUrl ->
                if (hasUpdate && latestVersion != null) {
                    showUpdateDialog(context, latestVersion, downloadUrl, releasePageUrl)
                }
            }
        }
    }
    
    // Main screen
    val buildCurrentReport: () -> String = {
        buildKeyboardDebugReport(
            context = context,
            recordStartedAtMs = recordStartedAtMs,
            events = recordedEvents,
            includeSuggestions = includeSuggestionsInExport
        )
    }
    val copyReportToClipboard: (String) -> Unit = { report ->
        val clipboardManager = context.getSystemService(Context.CLIPBOARD_SERVICE) as ClipboardManager
        clipboardManager.setPrimaryClip(
            ClipData.newPlainText("pastiera-keyboard-debug", report)
        )
        Toast.makeText(
            context,
            context.getString(R.string.debug_recorder_copied, recordedEvents.size),
            Toast.LENGTH_SHORT
        ).show()
    }
    val shareReport: (String) -> Unit = { report ->
        val shareIntent = Intent(Intent.ACTION_SEND).apply {
            type = "text/plain"
            putExtra(Intent.EXTRA_SUBJECT, "Pastiera Keyboard Debug Export")
            putExtra(Intent.EXTRA_TEXT, report)
        }
        context.startActivity(
            Intent.createChooser(shareIntent, context.getString(R.string.debug_recorder_share_chooser))
        )
    }

    Column(
        modifier = Modifier
            .fillMaxWidth()
            .verticalScroll(rememberScrollState()),
        horizontalAlignment = Alignment.CenterHorizontally,
        verticalArrangement = Arrangement.spacedBy(4.dp)
    ) {
        // Custom top bar with personalized graphics
        CustomTopBar(
            onSettingsClick = {
                val settingsIntent = Intent(context, SettingsActivity::class.java)
                context.startActivity(settingsIntent)
                (context as? Activity)?.let { activity ->
                    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.UPSIDE_DOWN_CAKE) {
                        activity.overrideActivityTransition(
                            Activity.OVERRIDE_TRANSITION_OPEN,
                            R.anim.slide_in_from_right,
                            0
                        )
                    } else {
                        @Suppress("DEPRECATION")
                        activity.overridePendingTransition(R.anim.slide_in_from_right, 0)
                    }
                }
            },
            modifier = Modifier.fillMaxWidth()
        )
        
        // Enable/select IME actions
        Row(
            modifier = Modifier
                .fillMaxWidth()
                .padding(horizontal = 16.dp),
            horizontalArrangement = Arrangement.spacedBy(8.dp)
        ) {
            Surface(
                modifier = Modifier
                    .weight(1f)
                    .heightIn(min = 44.dp)
                    .clickable {
                        val intent = Intent(Settings.ACTION_INPUT_METHOD_SETTINGS)
                        context.startActivity(intent)
                    }
            ) {
                Row(
                    modifier = Modifier
                        .fillMaxWidth()
                        .padding(horizontal = 10.dp, vertical = 8.dp),
                    verticalAlignment = Alignment.CenterVertically,
                    horizontalArrangement = Arrangement.spacedBy(8.dp)
                ) {
                    Icon(
                        imageVector = Icons.Filled.Keyboard,
                        contentDescription = null,
                        tint = MaterialTheme.colorScheme.primary,
                        modifier = Modifier.size(18.dp)
                    )
                    Text(
                        text = stringResource(R.string.enable_pastiera),
                        style = MaterialTheme.typography.labelLarge,
                        fontWeight = FontWeight.Medium,
                        maxLines = 1,
                        overflow = TextOverflow.Ellipsis,
                        modifier = Modifier.weight(1f)
                    )
                    Icon(
                        imageVector = if (!isPastieraEnabled) Icons.Filled.Warning else Icons.AutoMirrored.Filled.ArrowForward,
                        contentDescription = null,
                        tint = if (!isPastieraEnabled) MaterialTheme.colorScheme.error else MaterialTheme.colorScheme.onSurfaceVariant,
                        modifier = Modifier.size(16.dp)
                    )
                }
            }

            Surface(
                modifier = Modifier
                    .weight(1f)
                    .heightIn(min = 44.dp)
                    .clickable {
                        val imm = context.getSystemService(Context.INPUT_METHOD_SERVICE) as InputMethodManager
                        imm.showInputMethodPicker()
                    }
            ) {
                Row(
                    modifier = Modifier
                        .fillMaxWidth()
                        .padding(horizontal = 10.dp, vertical = 8.dp),
                    verticalAlignment = Alignment.CenterVertically,
                    horizontalArrangement = Arrangement.spacedBy(8.dp)
                ) {
                    Icon(
                        imageVector = Icons.Filled.Keyboard,
                        contentDescription = null,
                        tint = MaterialTheme.colorScheme.primary,
                        modifier = Modifier.size(18.dp)
                    )
                    Text(
                        text = stringResource(R.string.choose_input_method),
                        style = MaterialTheme.typography.labelLarge,
                        fontWeight = FontWeight.Medium,
                        maxLines = 1,
                        overflow = TextOverflow.Ellipsis,
                        modifier = Modifier.weight(1f)
                    )
                    Icon(
                        imageVector = if (isPastieraEnabled && !isPastieraSelected) Icons.Filled.Warning else Icons.AutoMirrored.Filled.ArrowForward,
                        contentDescription = null,
                        tint = if (isPastieraEnabled && !isPastieraSelected) MaterialTheme.colorScheme.error else MaterialTheme.colorScheme.onSurfaceVariant,
                        modifier = Modifier.size(16.dp)
                    )
                }
            }
        }

        // Test field
        OutlinedTextField(
            value = testText,
            onValueChange = { testText = it },
            modifier = Modifier
                .fillMaxWidth()
                .padding(horizontal = 16.dp),
            placeholder = { Text(stringResource(R.string.test_field_placeholder)) },
            minLines = 1,
            maxLines = 2,
            keyboardOptions = KeyboardOptions(
                capitalization = KeyboardCapitalization.Sentences
            )
        )

        // Recorder controls (always visible)
        Column(
            modifier = Modifier
                .fillMaxWidth()
                .padding(horizontal = 16.dp),
            verticalArrangement = Arrangement.spacedBy(4.dp)
        ) {
            Row(
                modifier = Modifier
                    .fillMaxWidth()
                    .horizontalScroll(rememberScrollState()),
                horizontalArrangement = Arrangement.spacedBy(8.dp),
                verticalAlignment = Alignment.CenterVertically
            ) {
                OutlinedButton(
                    onClick = {
                        if (isRecording) {
                            isRecording = false
                        } else {
                            recordedEvents.clear()
                            val startTime = System.currentTimeMillis()
                            recordStartedAtMs = startTime
                            lastRecordedAtMs = null
                            isRecording = true
                        }
                    }
                ) {
                    Text(
                        if (isRecording) {
                            stringResource(R.string.debug_recorder_stop)
                        } else {
                            stringResource(R.string.debug_recorder_record)
                        }
                    )
                }
                OutlinedButton(
                    onClick = {
                        recordedEvents.clear()
                        DebugCaptureStore.clearAll()
                        recordStartedAtMs = null
                        lastRecordedAtMs = null
                        isRecording = false
                        showDebugReportViewer = false
                        latestDebugReport = ""
                        displayedLastKeyEvent = null
                    }
                ) {
                    Text(stringResource(R.string.debug_recorder_clear))
                }
                OutlinedButton(
                    onClick = {
                        latestDebugReport = buildCurrentReport()
                        showDebugReportViewer = true
                    }
                ) {
                    Text(stringResource(R.string.debug_recorder_view))
                }
                OutlinedButton(
                    onClick = {
                        val report = buildCurrentReport()
                        shareReport(report)
                    }
                ) {
                    Text(stringResource(R.string.debug_recorder_share))
                }
                FilterChip(
                    selected = includeSuggestionsInExport,
                    onClick = {
                        includeSuggestionsInExport = !includeSuggestionsInExport
                    },
                    label = {
                        Text(
                            text = stringResource(R.string.debug_recorder_include_suggestions),
                            style = MaterialTheme.typography.labelSmall
                        )
                    }
                )
            }
            Text(
                text = context.getString(
                    R.string.debug_recorder_status,
                    if (isRecording) context.getString(R.string.debug_recorder_status_recording)
                    else context.getString(R.string.debug_recorder_status_stopped),
                    recordedEvents.size
                ),
                style = MaterialTheme.typography.bodySmall,
                fontFamily = FontFamily.Monospace,
                color = MaterialTheme.colorScheme.onSurfaceVariant
            )
            Text(
                text = "${stringResource(R.string.debug_recorder_started_at)}${
                    recordStartedAtMs?.let { formatDebugTimestamp(it) } ?: "n/a"
                }",
                style = MaterialTheme.typography.bodySmall,
                fontFamily = FontFamily.Monospace,
                color = MaterialTheme.colorScheme.onSurfaceVariant
            )
        }

        // Last keyboard event (always visible)
        val event = displayedLastKeyEvent
        Surface(
            modifier = Modifier
                .fillMaxWidth()
                .padding(horizontal = 16.dp)
        ) {
            Column(
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(12.dp),
                verticalArrangement = Arrangement.spacedBy(4.dp)
            ) {
                Row(
                    modifier = Modifier.fillMaxWidth(),
                    horizontalArrangement = Arrangement.spacedBy(8.dp)
                ) {
                    Column(
                        modifier = Modifier.weight(1f),
                        verticalArrangement = Arrangement.spacedBy(2.dp)
                    ) {
                        Text(
                            text = event?.keyCodeName ?: "n/a",
                            style = MaterialTheme.typography.bodyMedium,
                            fontFamily = FontFamily.Monospace
                        )
                        Text(
                            text = "${stringResource(R.string.event_action_label)}${event?.action ?: "n/a"}",
                            style = MaterialTheme.typography.bodyMedium,
                            fontFamily = FontFamily.Monospace
                        )
                        Text(
                            text = "${stringResource(R.string.event_keycode_label)}${event?.keyCode?.toString() ?: "n/a"}",
                            style = MaterialTheme.typography.bodyMedium,
                            fontFamily = FontFamily.Monospace
                        )
                        Text(
                            text = "Origin: ${event?.origin ?: "n/a"}",
                            style = MaterialTheme.typography.bodyMedium,
                            fontFamily = FontFamily.Monospace
                        )
                        Text(
                            text = "Layout: ${event?.resolvedLayout ?: "n/a"}",
                            style = MaterialTheme.typography.bodyMedium,
                            fontFamily = FontFamily.Monospace
                        )
                    }

                    Column(
                        modifier = Modifier.weight(1f),
                        verticalArrangement = Arrangement.spacedBy(2.dp)
                    ) {
                        Text(
                            text = "${stringResource(R.string.event_scancode_label)}${event?.scanCode?.toString() ?: "n/a"}",
                            style = MaterialTheme.typography.bodyMedium,
                            fontFamily = FontFamily.Monospace
                        )
                        Text(
                            text = "${stringResource(R.string.event_unicode_label)}${
                                event?.let {
                                    "raw=${formatUnicodeForDebug(it.rawUnicodeChar)} effective=${formatUnicodeForDebug(it.effectiveUnicodeChar)}"
                                } ?: "n/a"
                            }",
                            style = MaterialTheme.typography.bodyMedium,
                            fontFamily = FontFamily.Monospace
                        )
                        Text(
                            text = "${stringResource(R.string.event_output_label)}${
                                event?.outputKeyCodeName?.let {
                                    "$it${event.outputKeyCode?.let { code -> " ($code)" } ?: ""}"
                                } ?: "n/a"
                            }",
                            style = MaterialTheme.typography.bodyMedium,
                            fontFamily = FontFamily.Monospace,
                            color = if (event?.outputKeyCodeName != null) MaterialTheme.colorScheme.primary
                            else MaterialTheme.colorScheme.onSurface
                        )
                    }
                }

                Row(
                    modifier = Modifier.fillMaxWidth(),
                    verticalAlignment = Alignment.CenterVertically,
                    horizontalArrangement = Arrangement.SpaceBetween
                ) {
                    Text(
                        text = stringResource(R.string.last_keyboard_event_title),
                        style = MaterialTheme.typography.titleSmall,
                        fontWeight = FontWeight.Medium,
                        color = MaterialTheme.colorScheme.onSurfaceVariant
                    )
                    FilterChip(
                        selected = ignoreKeyboardCloseBackEvent,
                        onClick = { ignoreKeyboardCloseBackEvent = !ignoreKeyboardCloseBackEvent },
                        label = {
                            Text(
                                text = stringResource(R.string.ignore_back_short),
                                style = MaterialTheme.typography.labelSmall
                            )
                        }
                    )
                }

                if (event?.let { it.isShiftPressed || it.isCtrlPressed || it.isAltPressed } == true) {
                    Row(
                        horizontalArrangement = Arrangement.spacedBy(4.dp)
                    ) {
                        if (event.isShiftPressed) {
                            Surface(
                                color = MaterialTheme.colorScheme.primaryContainer,
                                shape = MaterialTheme.shapes.small
                            ) {
                                Text(
                                    text = stringResource(R.string.modifier_shift),
                                    style = MaterialTheme.typography.labelSmall,
                                    modifier = Modifier.padding(horizontal = 6.dp, vertical = 2.dp),
                                    fontWeight = FontWeight.Medium
                                )
                            }
                        }
                        if (event.isCtrlPressed) {
                            Surface(
                                color = MaterialTheme.colorScheme.primaryContainer,
                                shape = MaterialTheme.shapes.small
                            ) {
                                Text(
                                    text = stringResource(R.string.modifier_ctrl),
                                    style = MaterialTheme.typography.labelSmall,
                                    modifier = Modifier.padding(horizontal = 6.dp, vertical = 2.dp),
                                    fontWeight = FontWeight.Medium
                                )
                            }
                        }
                        if (event.isAltPressed) {
                            Surface(
                                color = MaterialTheme.colorScheme.primaryContainer,
                                shape = MaterialTheme.shapes.small
                            ) {
                                Text(
                                    text = stringResource(R.string.modifier_alt),
                                    style = MaterialTheme.typography.labelSmall,
                                    modifier = Modifier.padding(horizontal = 6.dp, vertical = 2.dp),
                                    fontWeight = FontWeight.Medium
                                )
                            }
                        }
                    }
                }
            }
        }

        if (showDebugReportViewer) {
            DebugReportViewerDialog(
                report = latestDebugReport,
                onDismiss = { showDebugReportViewer = false },
                onCopy = { copyReportToClipboard(latestDebugReport) },
                onShare = { shareReport(latestDebugReport) }
            )
        }
    }
}

private fun formatDebugTimestamp(timestampMs: Long): String {
    val formatter = SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSXXX", Locale.US)
    formatter.timeZone = TimeZone.getDefault()
    return formatter.format(Date(timestampMs))
}

private fun formatUnicodeForDebug(unicode: Int): String {
    if (unicode == 0) {
        return "0(n/a)"
    }
    val char = unicode.toChar()
    val printable = if (char.isISOControl()) "\\u%04X".format(unicode) else char.toString()
    return "$unicode('$printable')"
}

private fun flattenPreferenceValue(value: Any?): String {
    return when (value) {
        null -> "null"
        is Set<*> -> value.map { it.toString() }.sorted().joinToString(prefix = "[", postfix = "]")
        else -> value.toString()
    }
}

private fun sha256Hex(input: String): String {
    val digest = MessageDigest.getInstance("SHA-256")
    val bytes = digest.digest(input.toByteArray(Charsets.UTF_8))
    return bytes.joinToString("") { b -> "%02x".format(b) }
}

private fun formatHexInt(value: Int): String = "0x${value.toUInt().toString(16)}"

private data class KeyboardInputDeviceDebugInfo(
    val id: Int,
    val name: String,
    val descriptor: String,
    val vendorId: Int,
    val productId: Int,
    val keyboardType: Int,
    val sources: Int,
    val isExternal: Boolean,
    val isVirtual: Boolean
)

private fun keyboardInputDevicesSnapshot(): List<KeyboardInputDeviceDebugInfo> {
    val rows = mutableListOf<KeyboardInputDeviceDebugInfo>()
    val deviceIds: IntArray = InputDevice.getDeviceIds()
    for (id in deviceIds) {
        val device: InputDevice = InputDevice.getDevice(id) ?: continue
        val hasKeyboardSource =
            (device.sources and InputDevice.SOURCE_KEYBOARD) == InputDevice.SOURCE_KEYBOARD
        val hasKeyboardType = device.keyboardType != InputDevice.KEYBOARD_TYPE_NONE
        if (!hasKeyboardSource && !hasKeyboardType) {
            continue
        }
        rows.add(
            KeyboardInputDeviceDebugInfo(
                id = device.id,
                name = device.name ?: "unknown",
                descriptor = device.descriptor ?: "unknown",
                vendorId = device.vendorId,
                productId = device.productId,
                keyboardType = device.keyboardType,
                sources = device.sources,
                isExternal = device.isExternal,
                isVirtual = device.isVirtual
            )
        )
    }
    return rows
}

private data class SuggestionsExportRow(
    val timestampMs: Long,
    val entries: List<DebugCaptureStore.SuggestionEntry>,
    val repeatCount: Int
)

private fun buildFilteredSuggestionRows(
    snapshots: List<DebugCaptureStore.SuggestionsSnapshot>
): List<SuggestionsExportRow> {
    val nonEmpty = snapshots.filter { it.entries.isNotEmpty() }
    if (nonEmpty.isEmpty()) return emptyList()
    val rows = mutableListOf<SuggestionsExportRow>()
    nonEmpty.forEach { snapshot ->
        val last = rows.lastOrNull()
        if (last != null && last.entries == snapshot.entries) {
            rows[rows.lastIndex] = last.copy(
                timestampMs = snapshot.timestampMs,
                repeatCount = last.repeatCount + 1
            )
        } else {
            rows.add(
                SuggestionsExportRow(
                    timestampMs = snapshot.timestampMs,
                    entries = snapshot.entries,
                    repeatCount = 1
                )
            )
        }
    }
    return rows
}

private fun formatNullable(value: Boolean?): String = value?.toString() ?: "n/a"

private fun buildKeyboardDebugReport(
    context: Context,
    recordStartedAtMs: Long?,
    events: List<RecordedKeyboardEvent>,
    includeSuggestions: Boolean
): String {
    val nowMs = System.currentTimeMillis()
    val tz = TimeZone.getDefault()
    val prefs = SettingsManager.getPreferences(context)
    val imeContext = DebugCaptureStore.imeContextSnapshot()
    val autoCorrections = DebugCaptureStore.autoCorrectionsSnapshot()
    val suggestionsSnapshots = if (includeSuggestions) DebugCaptureStore.suggestionsSnapshot() else emptyList()
    val filteredSuggestionsRows = if (includeSuggestions) buildFilteredSuggestionRows(suggestionsSnapshots) else emptyList()
    val suggestionFilterMode = "empty_hidden,dedupe_consecutive"
    val inputDevices = keyboardInputDevicesSnapshot()
    val resolvedPhysicalProfile = DeviceSpecific.physicalKeyboardName()
    val settingsDump = prefs.all.entries
        .sortedBy { it.key }
        .joinToString("\n") { (key, value) -> "$key=${flattenPreferenceValue(value)}" }

    val header = buildString {
        appendLine("=== Pastiera Keyboard Debug Export ===")
        appendLine("exported_at=${formatDebugTimestamp(nowMs)}")
        appendLine("timezone_id=${tz.id}")
        appendLine("timezone_offset=${tz.getOffset(nowMs) / 1000}s")
        appendLine()
        appendLine("[system]")
        appendLine("android_release=${Build.VERSION.RELEASE ?: "unknown"}")
        appendLine("android_sdk=${Build.VERSION.SDK_INT}")
        appendLine("android_incremental=${Build.VERSION.INCREMENTAL ?: "unknown"}")
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
            appendLine("android_security_patch=${Build.VERSION.SECURITY_PATCH}")
        }
        appendLine()
        appendLine("[app]")
        appendLine("package=${context.packageName}")
        appendLine("version_name=${BuildConfig.VERSION_NAME}")
        appendLine("version_code=${BuildConfig.VERSION_CODE}")
        appendLine("build_type=${BuildConfig.BUILD_TYPE}")
        appendLine("flavor=${BuildConfig.FLAVOR}")
        appendLine("release_channel=${BuildConfig.RELEASE_CHANNEL}")
        appendLine()
        appendLine("[device]")
        appendLine("brand=${Build.BRAND}")
        appendLine("manufacturer=${Build.MANUFACTURER}")
        appendLine("model=${Build.MODEL}")
        appendLine("device=${Build.DEVICE}")
        appendLine("product=${Build.PRODUCT}")
        appendLine("fingerprint=${Build.FINGERPRINT}")
        appendLine("hardware=${Build.HARDWARE}")
        appendLine("board=${Build.BOARD}")
        appendLine("bootloader=${Build.BOOTLOADER}")
        appendLine("build_display=${Build.DISPLAY}")
        appendLine("build_id=${Build.ID}")
        appendLine("build_tags=${Build.TAGS}")
        appendLine("build_type=${Build.TYPE}")
        appendLine("supported_abis=${Build.SUPPORTED_ABIS.joinToString(",")}")
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
            appendLine("sku=${Build.SKU}")
            appendLine("odm_sku=${Build.ODM_SKU}")
            appendLine("soc_manufacturer=${Build.SOC_MANUFACTURER}")
        appendLine("soc_model=${Build.SOC_MODEL}")
        } else {
            appendLine("sku=n/a")
            appendLine("odm_sku=n/a")
            appendLine("soc_manufacturer=n/a")
            appendLine("soc_model=n/a")
        }
        appendLine("physical_keyboard_name=${DeviceSpecific.physicalKeyboardName()}")
        appendLine("keyboard_family=${DeviceSpecific.keyboardName()}")
        appendLine("profile_override=${SettingsManager.getPhysicalKeyboardProfileOverride(context)}")
        appendLine("resolved_physical_profile=$resolvedPhysicalProfile")
        appendLine()
        appendLine("[input_devices]")
        if (inputDevices.isEmpty()) {
            appendLine("(no keyboard-like input devices found)")
        } else {
            inputDevices.forEach { device ->
                appendLine(
                    "id=${device.id} name='${device.name}' descriptor='${device.descriptor}' " +
                        "vendor_id=${device.vendorId} product_id=${device.productId} " +
                        "keyboard_type=${device.keyboardType} sources=${device.sources} " +
                        "sources_hex=${formatHexInt(device.sources)} " +
                        "external=${device.isExternal} virtual=${device.isVirtual}"
                )
            }
        }
        appendLine()
        appendLine("[recording]")
        appendLine("started_at=${recordStartedAtMs?.let { formatDebugTimestamp(it) } ?: "n/a"}")
        appendLine("event_count=${events.size}")
        appendLine("include_suggestions=$includeSuggestions")
        appendLine("suggestions_filter=${if (includeSuggestions) suggestionFilterMode else "disabled"}")
        appendLine("attempt_logging_supported=true")
        appendLine()
        appendLine("[ime_context]")
        appendLine("captured_at=${imeContext?.timestampMs?.let { formatDebugTimestamp(it) } ?: "n/a"}")
        appendLine("target_package=${imeContext?.packageName ?: "n/a"}")
        appendLine("input_type=${imeContext?.inputType?.toString() ?: "n/a"}")
        appendLine("subtype_locale=${imeContext?.subtypeLocale ?: "n/a"}")
        appendLine("resolved_layout=${imeContext?.resolvedLayout ?: "n/a"}")
        appendLine("profile_override_snapshot=${imeContext?.physicalProfileOverride ?: "n/a"}")
        appendLine("resolved_physical_profile_snapshot=$resolvedPhysicalProfile")
        appendLine()
        appendLine("[settings_snapshot]")
        appendLine(settingsDump.ifBlank { "(empty)" })
        appendLine()
        appendLine("[autocorrections]")
        if (autoCorrections.isEmpty()) {
            appendLine("(no autocorrections recorded)")
        } else {
            autoCorrections.forEach { entry ->
                appendLine(
                    "${formatDebugTimestamp(entry.timestampMs)} | type=${entry.type} trigger=${entry.trigger} " +
                        "source=${entry.source} outcome=${entry.outcome} before='${entry.before}' " +
                        "after='${entry.after ?: "n/a"}' reason='${entry.reason ?: "n/a"}'"
                )
            }
        }
        if (includeSuggestions) {
            appendLine()
            appendLine("[suggestions]")
            if (filteredSuggestionsRows.isEmpty()) {
                appendLine("(no suggestion snapshots recorded)")
            } else {
                filteredSuggestionsRows.forEach { snapshot ->
                    val repeatSuffix = if (snapshot.repeatCount > 1) " x${snapshot.repeatCount}" else ""
                    appendLine(
                        "${formatDebugTimestamp(snapshot.timestampMs)} | " +
                            snapshot.entries.joinToString(", ") { "${it.candidate}{${it.source}}" } +
                            repeatSuffix
                    )
                }
            }
        }
        appendLine()
        appendLine("[events]")
    }

    val eventLines = if (events.isEmpty()) {
        listOf("(no recorded events)")
    } else {
        events.map { entry ->
            val event = entry.event
            val deltaPart = entry.deltaMs?.let { "+${it}ms" } ?: "start"
            val outputPart = if (event.outputKeyCodeName != null) {
                " output=${event.outputKeyCodeName}${event.outputKeyCode?.let { "($it)" } ?: ""}"
            } else {
                ""
            }
            "${formatDebugTimestamp(entry.wallTimestampMs)} | $deltaPart | ${event.action} | " +
                "origin=${event.origin} " +
                "key=${event.keyCodeName}(${event.keyCode}) scan=${event.scanCode} " +
                "deviceId=${event.deviceId} source=${event.source} " +
                "flags=${event.flags} repeat=${event.repeatCount} " +
                "meta=${event.metaState}(${formatHexInt(event.metaState)}) " +
                "unicode_raw=${formatUnicodeForDebug(event.rawUnicodeChar)} " +
                "unicode_effective=${formatUnicodeForDebug(event.effectiveUnicodeChar)} " +
                "alt=${event.isAltPressed} " +
                "shift=${event.isShiftPressed} ctrl=${event.isCtrlPressed} " +
                "altLatch=${formatNullable(event.altLatchActive)} altOneShot=${formatNullable(event.altOneShot)} " +
                "shiftLatch=${formatNullable(event.shiftLatchActive)} ctrlLatch=${formatNullable(event.ctrlLatchActive)} " +
                "symPage=${event.symPage?.toString() ?: "n/a"} layout=${event.resolvedLayout ?: "n/a"} " +
                "eventUptimeMs=${entry.uptimeTimestampMs?.toString() ?: "n/a"} " +
                "sourceHex=${formatHexInt(event.source)} flagsHex=${formatHexInt(event.flags)}$outputPart"
        }
    }.joinToString("\n")

    val payload = "$header$eventLines\n"
    val hash = sha256Hex(payload)
    return payload + "\nsha256=$hash\n"
}

/**
 * Checks if Pastiera IME is enabled and selected.
 * Uses InputMethodManager for Android 14+ compatibility.
 */
private fun checkImeStatus(
    context: Context,
    callback: (enabled: Boolean, selected: Boolean) -> Unit
) {
    try {
        val imm = context.getSystemService(Context.INPUT_METHOD_SERVICE) as InputMethodManager
        val pastieraPackageName = ImeIdentity.packageName
        val pastieraImeId = ImeIdentity.imeId
        
        // Check if Pastiera is enabled using InputMethodManager
        val enabledInputMethods = imm.enabledInputMethodList
        val isEnabled = enabledInputMethods.any { inputMethodInfo ->
            inputMethodInfo.packageName == pastieraPackageName ||
            ImeIdentity.matchesImeId(inputMethodInfo.id)
        }
        
        // Check if Pastiera is selected
        var isSelected = false
        if (isEnabled) {
            // Try to read DEFAULT_INPUT_METHOD
            // On Android 13 (API 33) it might still work even with targetSdk 36
            // On Android 14+ (API 34+) it will throw SecurityException
            try {
                val defaultInputMethod = android.provider.Settings.Secure.getString(
                    context.contentResolver,
                    android.provider.Settings.Secure.DEFAULT_INPUT_METHOD
                ) ?: ""
                isSelected = ImeIdentity.matchesImeId(defaultInputMethod)
            } catch (e: SecurityException) {
                // On Android 14+ (API 34+) with targetSdk 36, we can't read this setting
                // Try alternative method: check if we can get current input method info
                try {
                    // Alternative: check if our IME is in the list and try to infer selection
                    // This is not 100% reliable, but it's the best we can do
                    val currentSubtype = imm.currentInputMethodSubtype
                    if (currentSubtype != null) {
                        // If we have a subtype, check if it matches our package
                        // Note: This is a heuristic and may not be 100% accurate
                        val allInputMethods = imm.inputMethodList
                        val pastieraInputMethod = allInputMethods.find { 
                            it.packageName == pastieraPackageName || ImeIdentity.matchesImeId(it.id)
                        }
                        // If Pastiera is the only enabled IME, assume it's selected
                        if (pastieraInputMethod != null && enabledInputMethods.size == 1) {
                            isSelected = true
                        } else {
                            // We can't reliably determine, so assume not selected to show warning
                            isSelected = false
                        }
                    } else {
                        // Can't determine, assume not selected
                        isSelected = false
                    }
                } catch (e2: Exception) {
                    // If all methods fail, assume not selected
                    isSelected = false
                }
            } catch (e: Exception) {
                // Other exceptions, assume not selected
                isSelected = false
            }
        }
        
        callback(isEnabled, isSelected)
    } catch (e: Exception) {
        android.util.Log.e("MainActivity", "Error checking IME status", e)
        callback(false, false)
    }
}
